[project]
name = "fastapi-postgres-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.10.6",
    "python-multipart>=0.0.32",
    "pytest>=8.3.5",
    "uvicorn>=0.52.4",
    "ruff>=0.16.5",
    "mypy>=2.3.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
filterwarnings = [
    'ignore:.*Using `httpx` with `starlette.testclient` is deprecated; install `httpx2` instead\..*:starlette.exceptions.StarletteDeprecationWarning',
]
